import './assets/scss/style.scss'
import './assets/scss/news.scss'
import './assets/scss/dummy.scss'
import './assets/scss/production.scss'
import './assets/scss/generic.scss'
import './assets/scss/machinery.scss'
